### PR TITLE
update 09/11/59

### PR DESCRIPTION
**Pull request by dreammed**
fix
-tap tp play
-adventure mode select

change
-add loot scene

### CODE REVIEW

**Comment by Counter-pain** [comment]
dreammed why You not make your own publish? or update in Your fork/branch. I think I would better not just rely on daelus, because he seldom to online here

**Comment by dreammed** [comment]
hmm ok just for hot ifx

**Comment by Iquaridys** [comment]
sir can u change sort hero when lv 30? not pick with low start but high star first , or both 2 hero small star and 2 hero high star .

**Comment by dreammed** [comment]
not now

**Pull request merged**
